### PR TITLE
Remove shell ambiguity

### PR DESCRIPTION
**Pull request by blink1073**
cf https://github.com/Calysto/matlab_kernel/issues/88#issuecomment-285889345.

### CODE REVIEW

**Comment by blink1073** [comment]
@dsblank, I'll wait for you to concur on this one.

**Comment by dsblank** [comment]
Did you find a solution that you like? Still in progress?

**Comment by blink1073** [comment]
This is it, using cmd on Windows instead of guessing.

**Comment by dsblank** [comment]
Sounds good! Thanks!

**Pull request merged**
