### PR TITLE
Updated dot magic, with tests

### PR DESCRIPTION
**Pull request by dsblank**
This PR:

* updates the dot magic to work with current pydot
* adds tests for dot magics (cell and line)
* updates version

### CODE REVIEW

**Comment by dsblank** [comment]
@blink1073 How are you? I found some time to work on a couple of metakernel issues. I'm over my head on this one as I don't know github workflow syntax for how to install graphviz for the different OS test matrix entries.

**Comment by blink1073** [comment]
Hey @dsblank, I'm good, how are you?  I'll push some changes :)

**Comment by blink1073** [comment]
I think it would make sense to skip the pydot tests of graphviz is not installed, to make it easier to run the tests in other environments/OSes.

**Comment by dsblank** [comment]
@blink1073 Good idea! I skipped the tests when not on linux. Thank you for your help, as always!

**Comment by blink1073** [comment]
Let me know when you're ready for a release

**Comment by dsblank** [comment]
All ready for release! Thank you!

**Comment by blink1073** [comment]
Done!

**Pull request merged**
